@baseUrl = http://localhost:8080
@receiptId = 00000000-0000-0000-0000-000000000001

### Find by id receipt
GET {{baseUrl}}/api/v1/receipts/{{receiptId}}
Accept: application/json
Authorization: Bearer {{token}}
