@baseUrl = http://localhost:8080

### Update receipt
PUT {{baseUrl}}/api/v1/receipts/00000000-0000-0000-0000-000000000001
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "serviceOrderCode": "1",
  "amount": 200.00,
  "paymentMethod": "CREDIT_CARD",
  "notes": "Pagamento ajustado",
  "receivedByCode": "1"
}
