@baseUrl = http://localhost:8080
@serviceOrderCode = 1
@userCode = 1

### Cancel service order
### If the order is FINISHED, this action returns the products to stock
PATCH {{baseUrl}}/api/v1/service-orders/{{serviceOrderCode}}/cancel
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "changedByCode": "{{userCode}}",
  "notes": "Cliente desistiu do atendimento"
}
