@baseUrl = http://localhost:8080
@clientCode = 1
@vehicleCode = 1
@userCode = 1

### Create service order
POST {{baseUrl}}/api/v1/service-orders
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "clientCode": "{{clientCode}}",
  "vehicleCode": "{{vehicleCode}}",
  "responsibleTechnicianCode": "{{userCode}}",
  "status": "OPEN",
  "reportedProblem": "Motor falhando e consumo alto",
  "entryMileage": 125000,
  "fuelLevel": "1/2",
  "discount": 0.00,
  "serviceItems": [
    {
      "serviceCode": "1",
      "quantity": 1,
      "responsibleTechnicianCode": "{{userCode}}"
    }
  ],
  "productItems": [
    {
      "productCode": "1",
      "quantity": 1
    }
  ]
}
