@baseUrl = http://localhost:8080
@serviceOrderCode = 1
@userCode = 1

### Deliver service order
### Use only when the order is already FINISHED
PATCH {{baseUrl}}/api/v1/service-orders/{{serviceOrderCode}}/deliver
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "changedByCode": "{{userCode}}",
  "notes": "Veiculo entregue ao cliente"
}
