@baseUrl = http://localhost:8080

### Deliver service order
PATCH {{baseUrl}}/api/v1/service-orders/1/deliver
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "changedByCode": "1",
  "notes": "Veiculo entregue ao cliente"
}
