@baseUrl = http://localhost:8080
@page = 0
@size = 10
@sortField = openedAt
@sortDirection = desc

### Find all service orders
GET {{baseUrl}}/api/v1/service-orders?page={{page}}&size={{size}}&sort={{sortField}},{{sortDirection}}
Accept: application/json
Authorization: Bearer {{token}}
