@baseUrl = http://localhost:8080
@serviceOrderCode = 1

### Find by code service order
GET {{baseUrl}}/api/v1/service-orders/{{serviceOrderCode}}
Accept: application/json
Authorization: Bearer {{token}}
