@baseUrl = http://localhost:8080

### Finish service order
PATCH {{baseUrl}}/api/v1/service-orders/1/finish
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "changedByCode": "1",
  "notes": "Servico finalizado e pronto para retirada"
}
