@baseUrl = http://localhost:8080
@serviceOrderCode = 1
@userCode = 1

### Finish service order
### This action performs the stock output for product items
PATCH {{baseUrl}}/api/v1/service-orders/{{serviceOrderCode}}/finish
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "changedByCode": "{{userCode}}",
  "notes": "Servico finalizado e pronto para retirada"
}
