@baseUrl = http://localhost:8080
@stockMovementId = 00000000-0000-0000-0000-000000000001

### Find by id stock movement
GET {{baseUrl}}/api/v1/stock-movements/{{stockMovementId}}
Accept: application/json
Authorization: Bearer {{token}}
