@baseUrl = http://localhost:8080
@username = admin

### Refresh token
PUT {{baseUrl}}/auth/refresh/{{username}}
Authorization: {{refreshToken}}
Accept: application/json

> {%
client.global.set("token", response.body.body.accessToken);
client.global.set("refreshToken", response.body.body.refreshToken);
%}
