@baseUrl = http://localhost:8080
@username = admin
@password = 123456

### Login
POST {{baseUrl}}/auth/signin
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
