@baseUrl = http://localhost:8080
@username = arthenyo
@password = arthenyo

### Login
POST {{baseUrl}}/auth/signin
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
client.global.set("token", response.body.body.accessToken);
client.global.set("refreshToken", response.body.body.refreshToken);
%}
