@baseUrl = http://localhost:8080

### Create product category
POST {{baseUrl}}/api/v1/product-categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "Lubrificantes",
  "description": "Categoria de oleos, fluidos e lubrificantes"
}
