@baseUrl = http://localhost:8080
@enabled = true
@page = 0
@size = 10
@sortField = code
@sortDirection = asc

### Find all services
GET {{baseUrl}}/api/v1/services?enabled={{enabled}}&page={{page}}&size={{size}}&sort={{sortField}},{{sortDirection}}
Accept: application/json
Authorization: Bearer {{token}}
