@baseUrl = http://localhost:8080

### Create user
PUT {{baseUrl}}/api/v1/user/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "username": "arthenyo",
  "fullName": "Arthenyo Carlos Gonçalves Bandeira de Araújo",
  "email": "arthenyocarlos19@gmail.com",
  "password": "SUP@center2050",
  "roles": [
    "ROLE_ADMIN"
  ]
}
