@baseUrl = http://localhost:8080
@enabled = true
@page = 0
@size = 10
@sortField = code
@sortDirection = asc

### Find all Clients
GET {{baseUrl}}/api/v1/clients?enabled={{enabled}}&page={{page}}&size={{size}}&sort={{sortField}},{{sortDirection}}
Accept: application/json
Authorization: Bearer {{token}}
